# Generated by Django 6.0.4 on 2026-05-01 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actes', '0004_alter_actenaissance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeActe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enfant', models.CharField(max_length=100, verbose_name="Nom de l'enfant")),
                ('prenom_enfant', models.CharField(max_length=150, verbose_name="Prénom(s) de l'enfant")),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('reference_acte', models.CharField(blank=True, max_length=30, verbose_name="Référence de l'acte (si connue)")),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name="Commentaire de l'administrateur")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('acte_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='actes.actenaissance', verbose_name='Acte de naissance lié')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
            ],
            options={
                'verbose_name': "Demande d'acte",
                'verbose_name_plural': "Demandes d'actes",
                'ordering': ['-date_creation'],
            },
        ),
    ]
