# Generated by Django 6.0.4 on 2026-04-23 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_agent', models.CharField(max_length=20, unique=True, verbose_name='Code agent (ex: AG-8821)')),
                ('secteur', models.CharField(max_length=150, verbose_name="Secteur d'intervention (ex: Kindia Centre)")),
                ('centre_etat_civil', models.CharField(blank=True, max_length=200, verbose_name="Centre d'état civil rattaché")),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('conge', 'En congé'), ('inactif', 'Inactif')], default='actif', max_length=20, verbose_name='Statut')),
                ('est_en_ligne', models.BooleanField(default=False, verbose_name='En ligne')),
                ('derniere_activite', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('latitude_actuelle', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude GPS actuelle')),
                ('longitude_actuelle', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude GPS actuelle')),
                ('precision_gps', models.IntegerField(blank=True, null=True, verbose_name='Précision GPS (en mètres)')),
                ('gps_mis_a_jour_le', models.DateTimeField(blank=True, null=True, verbose_name='Dernière mise à jour GPS')),
                ('objectif_hebdomadaire', models.IntegerField(default=50, verbose_name='Objectif hebdomadaire (actes)')),
                ('taux_sync_blockchain', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux de synchronisation blockchain (%)')),
                ('niveau_batterie', models.IntegerField(blank=True, null=True, verbose_name='Niveau de batterie du terminal (%)')),
                ('version_application', models.CharField(default='1.0.0', max_length=20, verbose_name="Version de l'application")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agent', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur')),
            ],
            options={
                'verbose_name': 'Agent de terrain',
                'verbose_name_plural': 'Agents de terrain',
                'ordering': ['-derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='AlerteZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'alerte")),
                ('description', models.TextField(verbose_name='Description')),
                ('region', models.CharField(max_length=50, verbose_name='Région concernée')),
                ('type_alerte', models.CharField(default='SECURITE', max_length=20, verbose_name="Type d'alerte")),
                ('est_active', models.BooleanField(default=True, verbose_name='Alerte active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('agents_concernes', models.ManyToManyField(blank=True, related_name='alertes', to='agents.agent', verbose_name='Agents concernés')),
            ],
            options={
                'verbose_name': 'Alerte de zone',
                'verbose_name_plural': 'Alertes de zone',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EvenementActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evt', models.CharField(max_length=30, verbose_name="Type d'événement")),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='agents.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': "Événement d'activité",
                'verbose_name_plural': "Événements d'activité",
                'ordering': ['-date_creation'],
            },
        ),
    ]
