# Generated by Django 6.0.4 on 2026-04-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naissance',
            name='Prenoms_enfant',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
