# Generated by Django 6.0.4 on 2026-04-24 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes', '0002_naissance_prenoms_enfant'),
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enfant', models.CharField(max_length=150)),
                ('prenoms_enfant', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('nom_mere', models.CharField(max_length=150)),
                ('nom_pere', models.CharField(blank=True, max_length=150)),
                ('poids', models.FloatField(blank=True, null=True)),
                ('taille', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut_sync', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SYNCHRONISE', 'Synchronisé'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20, verbose_name='Statut Blockchain')),
                ('hash_unique', models.CharField(blank=True, max_length=256, unique=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_enregistres', to='agents.agent')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acte de naissance',
                'verbose_name_plural': 'Actes de naissance',
            },
        ),
        migrations.DeleteModel(
            name='Naissance',
        ),
    ]
