# Generated by Django 6.0.4 on 2026-04-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes', '0003_actenaissance_delete_naissance'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actenaissance',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Acte de naissance', 'verbose_name_plural': 'Actes de naissance'},
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='hash_unique',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='prenoms_enfant',
        ),
        migrations.RemoveField(
            model_name='actenaissance',
            name='taille',
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='biometrie_mere',
            field=models.ImageField(blank=True, null=True, upload_to='actes/biometrie/%Y/%m/', verbose_name='Empreinte biométrique mère'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='centre_etat_civil',
            field=models.CharField(blank=True, max_length=200, verbose_name="Centre d'état civil"),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='date_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de synchronisation'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='est_brouillon',
            field=models.BooleanField(default=False, verbose_name='Sauvegardé en brouillon'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='hash_blockchain',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hash blockchain'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='heure_naissance',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de naissance'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='index_bloc',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Index du bloc'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='latitude_enregistrement',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Latitude de l'enregistrement"),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='longitude_enregistrement',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name="Longitude de l'enregistrement"),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='mere_verifiee',
            field=models.BooleanField(default=False, verbose_name='Identité mère vérifiée'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='mode_hors_ligne',
            field=models.BooleanField(default=False, verbose_name='Enregistré hors ligne'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='nin_pere',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIN du père'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='pere_present',
            field=models.BooleanField(default=False, verbose_name='Père présent lors de la déclaration'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='pere_verifie',
            field=models.BooleanField(default=False, verbose_name='Identité père vérifiée'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='photo_enfant',
            field=models.ImageField(blank=True, null=True, upload_to='actes/photos_enfants/%Y/%m/', verbose_name="Photo de l'enfant"),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='precision_gps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Précision GPS (m)'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='prefecture',
            field=models.CharField(default='Conakry', max_length=100, verbose_name='Préfecture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='prenom_enfant',
            field=models.CharField(default='Inconnu', max_length=150, verbose_name="Prénom(s) de l'enfant"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='profession_mere',
            field=models.CharField(blank=True, max_length=100, verbose_name='Profession de la mère'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='actes/qrcodes/%Y/%m/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='reference',
            field=models.CharField(default='REF-TEMP', editable=False, max_length=30, unique=True, verbose_name='Référence (ex: NC-2024-8842)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='region_naissance',
            field=models.CharField(default='Boké', max_length=50, verbose_name='Région'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='signature_agent',
            field=models.TextField(blank=True, verbose_name='Signature cryptographique agent'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='sous_prefecture',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sous-préfecture'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Hash de transaction'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='actes', to='agents.agent', verbose_name='Agent responsable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='lieu_naissance',
            field=models.CharField(max_length=200, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_enfant',
            field=models.CharField(max_length=100, verbose_name="Nom de l'enfant"),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_mere',
            field=models.CharField(max_length=200, verbose_name='Nom complet de la mère'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='nom_pere',
            field=models.CharField(max_length=200, verbose_name='Nom complet du père'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='actenaissance',
            name='statut_sync',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('synchronise', 'Synchronisé'), ('erreur', 'Erreur')], default='en_attente', max_length=20, verbose_name='Statut de synchronisation'),
        ),
    ]
