# Generated by Django 6.0.4 on 2026-04-22 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('role', models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin_national', 'Administrateur National'), ('admin_prefectoral', 'Administrateur Préfectoral'), ('agent_terrain', 'Agent de Terrain'), ('superviseur', 'Superviseur Régional'), ('citoyen', 'Citoyen')], default='agent_terrain', max_length=30, verbose_name='Rôle')),
                ('region', models.CharField(choices=[('conakry', 'Conakry'), ('kindia', 'Kindia'), ('boke', 'Boké'), ('mamou', 'Mamou'), ('labe', 'Labé'), ('kankan', 'Kankan'), ('faranah', 'Faranah'), ('nzerekore', 'Nzérékoré'), ('national', 'National (toutes régions)')], default='conakry', max_length=20, verbose_name="Région d'intervention")),
                ('prefecture', models.CharField(blank=True, max_length=100, verbose_name='Préfecture')),
                ('sous_secteur', models.CharField(blank=True, max_length=100, verbose_name='Sous-secteur')),
                ('identifiant_agent', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Identifiant Agent')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('est_suspendu', models.BooleanField(default=False, verbose_name='Compte suspendu')),
                ('is_staff', models.BooleanField(default=False, verbose_name="Accès à l'administration")),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('langue_preferee', models.CharField(choices=[('fr', 'Français'), ('ss', 'Soussou'), ('ff', 'Peul (Fula)'), ('ml', 'Malinké')], default='fr', max_length=2, verbose_name='Langue préférée')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='JournalConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_tente', models.EmailField(max_length=254, verbose_name='Email utilisé')),
                ('adresse_ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('succes', models.BooleanField(default=False, verbose_name='Connexion réussie')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('user_agent', models.TextField(blank=True, verbose_name='Agent navigateur')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de connexion',
                'verbose_name_plural': 'Journaux de connexion',
                'ordering': ['-horodatage'],
            },
        ),
    ]
