# Generated by Django 6.0.4 on 2026-04-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='est_actif',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_admin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code administration'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='langue_preferee',
            field=models.CharField(choices=[('fr', 'Français'), ('ss', 'Soussou'), ('ff', 'Peul (Fula)'), ('ml', 'Malinké'), ('en', 'Anglais')], default='fr', max_length=10, verbose_name='Langue préférée'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_utilisateurs/%Y/%m/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='region',
            field=models.CharField(blank=True, choices=[('CONAKRY', 'Zone Spéciale de Conakry'), ('BOKE', 'Région de Boké'), ('KINDIA', 'Région de Kindia'), ('MAMOU', 'Région de Mamou'), ('LABE', 'Région de Labé'), ('FARANAH', 'Région de Faranah'), ('KANKAN', 'Région de Kankan'), ('NZEREKORE', 'Région de Nzérékoré'), ('NATIONAL', 'National (toutes régions)')], max_length=20, verbose_name="Région d'affectation"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin_national', 'Administrateur National'), ('admin_prefectoral', 'Administrateur Préfectoral'), ('superviseur', 'Superviseur'), ('agent_terrain', 'Agent de Terrain'), ('citoyen', 'Citoyen')], default='citoyen', max_length=30, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='sous_secteur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sous-secteur / Quartier'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
