# Generated by Django 6.0.4 on 2026-04-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_est_actif_utilisateur_is_active_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='date_inscription',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='photo_profil',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='code_admin',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='derniere_connexion',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='est_suspendu',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='langue_preferee',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='sous_secteur',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_connexion_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP de connexion'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='identifiant_agent',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Identifiant agent'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Accès administration'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom(s)'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='region',
            field=models.CharField(blank=True, choices=[('conakry', 'Conakry'), ('kindia', 'Kindia'), ('boke', 'Boké'), ('labe', 'Labé'), ('kankan', 'Kankan'), ('faranah', 'Faranah'), ('nzerekore', 'Nzérékoré'), ('mamou', 'Mamou')], max_length=20, verbose_name="Région d'affectation"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin_national', 'Administrateur National'), ('admin_prefectoral', 'Administrateur Préfectoral'), ('agent', 'Agent de Terrain'), ('citoyen', 'Citoyen')], default='citoyen', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='JournalConnexion',
        ),
    ]
